server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      zone1: http://service-registry:8761/eureka/
    region: region1
    availability-zones:
      region1: zone1
  instance:
    hostname: service-registry
    metadata-map:
      zone: zone1