version: '3'
services:
  service-registry:
    container_name: service-registry
    hostname: service-registry
    image: service-registry:latest
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  docker-mysql-activity:
    image: mysql:latest
    container_name: docker-mysql-activity
    volumes:
    - mysql_activity:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_DATABASE=SCactivity
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=testuser@123
  docker-mysql-authentication:
    image: mysql:latest
    container_name: docker-mysql-authentication
    volumes:
    - mysql_authentication:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=sportingCenter
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
  docker-mysql-subscription:
    image: mysql:latest
    container_name: docker-mysql-subscription
    volumes:
      - mysql_subscription:/var/lib/mysql
    ports:
      - 33062:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=SCSubscription
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
  docker-mysql-calendar:
    image: mysql:latest
    container_name: docker-mysql-calendar
    volumes:
    - mysql_calendar:/var/lib/mysql
    ports:
      - 33063:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=SCcalendar
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123

  activity-service:
    image: activity-service:latest
    container_name: activity-service
    environment:
      - SPRING_APPLICATION_NAME=activity-service
    hostname: activity-service
    build:
      context: ./activity-service
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - service-registry
      - docker-mysql-activity
  zuul-service:
    image: zuul-service:latest
    container_name: zuul-service
    environment:
      - SPRING_APPLICATION_NAME=zuul-service
    hostname: zuul-service
    build:
      context: ./zuulsvr
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - service-registry
  authentication-service:
    image: authentication-service:latest
    container_name: authentication-service
    environment:
      - SPRING_APPLICATION_NAME=authentication-service
    hostname: authentication-service
    build:
      context: ./BackENDSportingCenter/spring-boot-oauth2-social-login
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - service-registry
      - docker-mysql-authentication
  subscription-service:
    image: subscription-service:latest
    container_name: subscription-service
    environment:
      - SPRING_APPLICATION_NAME=subscription-service
    hostname: subscription-service
    build:
      context: ./subscription-service
      dockerfile: Dockerfile
    ports:
    - 9002:9002
    depends_on:
      - service-registry
      - docker-mysql-subscription
  calendar-service:
    image: calendar-service:latest
    container_name: calendar-service
    environment:
      - SPRING_APPLICATION_NAME=calendar-service
    hostname: calendar-service
    build:
      context: ./calendar-service
      dockerfile: Dockerfile
    ports:
    - 9003:9003
    depends_on:
      - service-registry
      - docker-mysql-calendar

volumes:
  mysql_activity:
  mysql_subscription:
  mysql_calendar:
  mysql_authentication:



