kind: Service
apiVersion: v1
metadata:
  name: calendar-service
  labels:
    name: calendar-service
spec:
  ports:
    - nodePort: 30005
      port: 9003
      targetPort: 9003
      protocol: TCP
  selector:
    app: calendar-service
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-service
spec:
  selector:
    matchLabels:
      app: calendar-service
  replicas: 1
  template:
    metadata:
      labels:
        app: calendar-service
    spec:
      containers:
        - name: cal-service
          image: taasproject/calendar-service:latest
          ports:
            - containerPort: 9003
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-calendar  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-calendar
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password