apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: taasproject/service-registry:latest
          ports:
            - containerPort: 8761
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30000
  type: LoadBalancer
