#spring:
  #application:
    #name: API-GATEWAY-ZUUL
  #profiles:
    #active:
      #default
  #cloud:
    #config:
      #enabled: true

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

#eureka:
  #instance:
    #preferIpAddress: true
  #client:
    #registerWithEureka: true
    #fetchRegistry: true
    #serviceUrl:
        #defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    register-with-eureka: true
    service-url:
      zone1: http://service-registry:8761/eureka/
    prefer-same-zone-eureka: true
    region: region1
    availability-zones:
      region1: zone1
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1


