server:
  port: 9002

#spring:
  #application:
    #name: SUBSCRIPTION-SERVICE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-mysql-subscription:3306/SCSubscription?createDatabaseIfNotExist=true
    username: testuser
    password: testuser@123
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  client:
    register-with-eureka: true
    service-url:
      zone1: http://service-registry:8761/eureka/
    prefer-same-zone-eureka: true
    region: region1
    availability-zones:
      region1: zone1
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1