logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

spring:
  application:
    name: API-GATEWAY-ZUUL
  profiles:
    active: "dev"

server:
  port: 5555

---

spring:
  profiles: dev
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: prod
eureka:
  client:
    register-with-eureka: true
    service-url:
      zone1: http://service-registry:8761/eureka/
    prefer-same-zone-eureka: true
    region: region1
    availability-zones:
      region1: zone1
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
    hostname: zuul-service




